name: Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: "${{ ec2-99-79-60-146.ca-central-1.compute.amazonaws.com	}}"
          username: "${{ neha }}"
          key: "${{ 0105e1f0b5b2c2429 }}"
          port: "${{ 22 }}"
          script: |
            # Run your commands on the EC2 instance
            # Example: echo "Hello from EC2!"
            echo "Hello from EC2!"
