name: Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          script: |
              ssh -i C:/Program Files/Amazon/AWSCLIV2/ec2_pipeline.pem neha@ec2-99-79-67-77.ca-central-1.compute.amazonaws.com 'echo "Hello from EC2!"'

          host: ec2-99-79-67-77.ca-central-1.compute.amazonaws.com
          username: neha
          key: |
            -----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAj0PSb5G6KISPgTmIfNaStW6Hmv8pT/EJzfjsQOngwenbu8rL\nqARBXS694Q/ck3u+zzRJBY+4qtlf1iJHgXPOFPZKwoQPWbjK/WPHtIut7pgKA9wF\nwzLz7rV1MBuUHYM3mK60VVTbe8XWwJCyEJqUh7MwVXsuu0yNSgPulnsZN5uYzhEu\nNTqYZHrhIKpJiv9cWfLI33yayCiuH5UE0Icqa4cJkcgsqv3OYj05faXWydy2exYe\nAok7ppoTfQ3Da3vj3DYdIWJvOFTIE0ndmSG9zSoe27cYIdb0ojevDsP0+rApB/9x\n/wZXBqlM/h0GzpLCL95TI/I0wO/3sMLA2paCvQIDAQABAoIBAD8tBUs11AWyDyZJ\nHKsQZDmluB7djnY2MMCnmGc3u2lHmyJA13YMClbxGcJ5oCdZVldBE0Jkkmak3OIs\n06N+Uc5knasRWUOTfdAnhBVV0yl32lLBX7koavFFC5xfTP2Gs6mcwOEwPmliYMUi\nCaPQxtbgadwIKh9mLpgJC9lIB2LBjZEjJAU4gqj3oYE3HU4K37o28wZrHEf4/EDE\nc/RlgJAxDPK5aEJlTi3rAy/qsxZZdHPgSfma7nYroQq5D8lIcFJVA+bXxuv1KTSK\nbx/4ypvowoWbh6KSAEgA0bBwAxh9k/lPS+YXJgA3TVCP62gt/ZOajThXsObbK9hC\nQ9zDZoECgYEAySq9GA04t1jt02MPqFHgsSnsmhJoM+5FLebIhLRk65a1MgA6j0jH\nzG9ghEOxAMWuDcVvArLfQX7Xs4DZR0r779C1FLDqZviLf5FTe5duwsoXj2s/AYMt\nnae5CGqbwUyycXYtgKedJTz2D9Hp9nm0X4FcqoItikTDMGwVMVFfe5UCgYEAtlC6\nnjbHKx8W5lUJguH0RpXDPWMeFhvILi4XikWBjOjcNrT3AAePil7ruLVQ0+GPVF5O\nFXKy3sGWuqLcaa5ntAd9AmGyRIWxo7InY5RtDJ2igEnmfC+sHRlz+IPBsyBBSGRm\n7QGjIDgPmRX461bOGzxOan44qTjsX6IYSEov4IkCgYEAvSDYXPd5Pi92kUnOG7K2\n6/l9f7EUlNZL5gbWuKUdSL0NJ7A9Xh7P8W05McCudgpkRIA9iS0AZwRI6XOXU8a0\nrFftF0Hpbtv30vyfn0/VC3+SvPzYZKSey103wijwvMBN+AxiZVWwkaUJtf/l1hvA\nMBZgN9Jh3GAfnrPPDOnzOi0CgYAiO9Ju9vY7IKFaKsmYa/lEb8azdjMmD51tHnaJ\nHjgPT4JaO2zN8p1/bAdzLYi54HbbbsHWwSzZKxy0evRMW9VZNrbAhbvFph0PEdrX\nlf1MCyWCVV4UH5d/91GRbpwmmH3prACvrEkHOb+kDT4qYqhc8NwAnybgj7HC21sX\n5+ZJkQKBgCgFyOoJgtlLa0pTgn9UVzMb2LzVlkRTX0LJFXq0Dm5oAXXq2kILqB9Z\ntSODI++3+JRbfCHZ10tK8w5VGE7yRfdPG/qaTd6HOcF4xusVgRduXsfK0WtIf6bv\nF8yzusgHLlv3f4JITKjZ5XzBBMXawavevDIUy/5SigAYJxFBT4ln-----END RSA PRIVATE KEY-----
