name: Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          script: |
              ssh -i C:/Program Files/Amazon/AWSCLIV2/ec2_pipeline.pem neha@ec2-99-79-67-77.ca-central-1.compute.amazonaws.com 'echo "Hello from EC2!"'

          host: ec2-99-79-67-77.ca-central-1.compute.amazonaws.com
          username: neha
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAj0PSb5G6KISPgTmIfNaStW6Hmv8pT/EJzfjsQOngwenbu8rL
            qARBXS694Q/ck3u+zzRJBY+4qtlf1iJHgXPOFPZKwoQPWbjK/WPHtIut7pgKA9wF
            wzLz7rV1MBuUHYM3mK60VVTbe8XWwJCyEJqUh7MwVXsuu0yNSgPulnsZN5uYzhEu
            NTqYZHrhIKpJiv9cWfLI33yayCiuH5UE0Icqa4cJkcgsqv3OYj05faXWydy2exYe
            Aok7ppoTfQ3Da3vj3DYdIWJvOFTIE0ndmSG9zSoe27cYIdb0ojevDsP0+rApB/9x
            /wZXBqlM/h0GzpLCL95TI/I0wO/3sMLA2paCvQIDAQABAoIBAD8tBUs11AWyDyZJ
            HKsQZDmluB7djnY2MMCnmGc3u2lHmyJA13YMClbxGcJ5oCdZVldBE0Jkkmak3OIs
            06N+Uc5knasRWUOTfdAnhBVV0yl32lLBX7koavFFC5xfTP2Gs6mcwOEwPmliYMUi
            CaPQxtbgadwIKh9mLpgJC9lIB2LBjZEjJAU4gqj3oYE3HU4K37o28wZrHEf4/EDE
            c/RlgJAxDPK5aEJlTi3rAy/qsxZZdHPgSfma7nYroQq5D8lIcFJVA+bXxuv1KTSK
            bx/4ypvowo
          
