name: Push to ECR

on:
  push:
    branches:
      - feature_neha  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker
        uses: actions/setup-docker@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1 
          
      - name: Log in to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 058264132523.dkr.ecr.ca-central-1.amazonaws.com
        
      - name: Run script to push images
        run: |
          chmod +x push_to_ecr.sh
          ./push_to_ecr.sh
